### ISSUE TITLE
Distorted picture

### ISSUE THREAD

**Issue by clinging-al** [updeshxp/scrcpy-android#1]
This is an excellent project, thank you very much for your efforts. But when I try to project the TV screen to the mobile phone (I want to switch the program through the mobile phone), the screen is distorted, and I can't help it horizontally. Or I want to get a 1080x1920 picture instead of 1920x1080.
look:
https://pics.images.ac.cn/image/5ed463e96a69d.html

**Comment by updeshxp** [comment]
This is being worked on currently.

**Comment by updeshxp** [comment]
This is an older version as original author has released a new version:
https://gitlab.com/las2mile/scrcpy-android
Could you Please check on the same if this issue is present.
