### ISSUE TITLE
I use it to control the TV box, the TV box is horizontal, and the phone is a vertical screen, the coordinates will be messy. And when the horizontal screen is opened, the layout is wrong, and the input box is not visible

### ISSUE THREAD

**Issue by djbone** [updeshxp/scrcpy-android#2]
I use it to control the TV box, the TV box is horizontal, and the phone is a vertical screen, the coordinates will be messy. And when the horizontal screen is opened, the layout is wrong, and the input box is not visible

**Comment by updeshxp** [comment]
See #1 , This is being worked on.

**Comment by updeshxp** [comment]
This is an older version as original author has released a new version:
https://gitlab.com/las2mile/scrcpy-android
Could you Please check on the same if this issue is present.
