### ISSUE TITLE
It need to be updated

### ISSUE THREAD

**Issue by tz527129804** [updeshxp/scrcpy-android#3]
Delay is too high，maybe new server version（1.14） can solve it.
I'm not a programmer ，so which big brother can update the scrcpy to v1.14 ？
Aslo，the Screen Resolution and Code Rate should be higeher ~
Wait for the big brother to take me to fly ~😀

**Comment by MakerChetan** [comment]
Hi Updesh,
Nice work!
Is it possible to control target device with server app from web browser on any client device (i.e without installing app on client) ?

**Comment by updeshxp** [comment]
@MakerChetan I don't think this is possible.

**Comment by updeshxp** [comment]
This is an older version as original author has released a new version:
https://gitlab.com/las2mile/scrcpy-android
Could you Please check on the same if this issue is present.
