### ISSUE TITLE
Is it possible to custom resolution?

### ISSUE THREAD

**Issue by wuuconix** [updeshxp/scrcpy-android#5]
I succesffully scrcpy my phone to my pad！Thanks for your hard working!
But I foud something can prove.
Nowadays many smartphone are not 16:9，but in app we cannot custom the resolution mannuly which caused the image stretched.
Another thing, is it possible that makes the app float in the pad for example which like little window. 
Sincerely Looking forward for your reply!

**Comment by updeshxp** [comment]
This is an older version as original author has released a new version:
https://gitlab.com/las2mile/scrcpy-android
Could you Please check on the same if this issue is present.

**Comment by wuuconix** [comment]
thx
