### ISSUE TITLE
Is it support multi-touch?

### ISSUE THREAD

**Issue by airhandsome** [updeshxp/scrcpy-android#6]
I have tried some game which required multi-touch in scrcpy. However, it seems didn't work. For example, if I use my left finger to control to direction and user my right finger to control jump. When I entered the jump button with my right finger, the left finger didn't leave the screen and the character stop move. Is there some method to fix it?

**Comment by updeshxp** [comment]
This is an older version as original author has released a new version:
https://gitlab.com/las2mile/scrcpy-android
Could you Please check on the same if this issue is present.
